---
title: "Data Project"
---

The purpose of the data project is for you to conduct a reproducible analysis with a data set of your choosing. You are to use a statistical procedure from this class (i.e. null hypothesis test). There are two components to the project, the proposal, which will be graded on a pass/fail basis, and the final report. The outline for each of these are provided below. Suggestions for possible data sources are included below, however you are free to use data not listed below. The only requirement is that you are allowed to share the data. Projects will be shared with others on this website so should be presented in a way that other students can reproduce your analysis.

## Grading Rubric

```{r, echo=FALSE, results='asis'}
options(knitr.kable.NA = '')
rubric <- readxl::read_excel('assignments/Data_Project_Rubric.xlsx')
rubric |>
	knitr::kable(format = 'html',
				 escape = FALSE)
```


## Proposal Outline

* Research question
* What are the cases, and how many are there?
* Describe the method of data collection.
* What type of study is this (observational/experiment)?
* Data Source: If you collected the data, state self-collected. If not, provide a citation/link.
* Response: What is the response variable, and what type is it (numerical/categorical)?
* Explanatory: What is the explanatory variable(s), and what type is it (numerical/categorical)?
* Relevant summary statistics
* What statistical test will you perform?

## Final Project

Checklist / Suggested Outline

* Overview slide
	* Context on the data collection
	* Description of the dependent variable (what is being measured)
	* Description of the independent variable (what is being measured; include at least 2 variables)
	* Research question
* Summary statistics
* Include appropriate data visualizations.
* Statistical output
	* Include the appropriate statistics for your method used.
	* For null hypothesis tests (e.g. t-test, chi-squared, ANOVA, etc.), state the null and alternative hypotheses along with relevant statistic and p-value (and confidence interval if appropriate).
* Conclusion
	* Why is this analysis important?
	* Limitations of the analysis?


## Example Data Sources

You are not to use data sources used in class or the textbooks. Possible data sources include, but are not limited to:

* FiveThirtyEight [https://github.com/fivethirtyeight/data](https://github.com/fivethirtyeight/data)
* RStudio data sources [http://blog.rstudio.org/2014/07/23/new-data-packages/](http://blog.rstudio.org/2014/07/23/new-data-packages/)
* Analyze Survey Data for Free (ASDFree) has many open data sources that can be used [http://www.asdfree.com/](http://www.asdfree.com/)
* The World Bank Data Catalog [http://datacatalog.worldbank.org/](http://datacatalog.worldbank.org/)
* Google Public Data search engine [http://www.google.com/publicdata/directory](http://www.google.com/publicdata/directory)
* Vanderbilt data sources [http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets](http://biostat.mc.vanderbilt.edu/wiki/Main/DataSets)
* Programme of International Student Assessment (PISA) [http://www.oecd.org/pisa/](http://www.oecd.org/pisa/)
* Behavioral Risk Factor Surveillance System (BRFSS) [http://www.cdc.gov/brfss/](http://www.cdc.gov/brfss/)
* World Values Survey [http://www.worldvaluessurvey.org/wvs.jsp](http://www.worldvaluessurvey.org/wvs.jsp)
* American National Election Survey (ANES) [http://www.electionstudies.org/](http://www.electionstudies.org/)
* General Social Survey (GSS) [http://www3.norc.org/GSS+Website/](http://www3.norc.org/GSS+Website/)
* Integrated Postsecondary Education Data System (IPEDS) [https://nces.ed.gov/ipeds/](https://nces.ed.gov/ipeds/)
* U.S. Census and American Community Survey [https://cran.r-project.org/web/packages/acs/index.html](https://cran.r-project.org/web/packages/acs/index.html)
* [10 Standard Datasets for Practicing Applied Machine Learning](https://machinelearningmastery.com/standard-machine-learning-datasets/)
* [Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets)
* [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php) - See also this R package: https://github.com/tyluRp/ucimlr
* [OpenML](https://www.openml.org/search?type=data&sort=runs&status=active)
